cloud-collab:
  image: learnersguild/cloud-collab-docker
  tty: true
  environment:
    # DON'T COMMIT YOUR CHANGES HERE -- these are in here for ease-of-deployment using Tutum!
    FLOOBITS_API_KEY: <YOUR FLOOBITS USERNAME>
    FLOOBITS_SECRET: <YOUR FLOOBITS USERNAME>
    FLOOBITS_USERNAME: <YOUR FLOOBITS USERNAME>
    FLOOBITS_WORKSPACE_URL: <YOUR FLOOBITS WORKSPACE URL>
